# Generated by Django 3.2.4 on 2021-06-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mashena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('color', models.CharField(max_length=250)),
                ('type', models.IntegerField(default=0)),
                ('vloyat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.vloyat')),
                ('zavod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.zavod')),
            ],
        ),
    ]
